// Workflow — the automation engine definition.
// A workflow is a directed graph: trigger → conditions → nodes → actions.
// Stored as JSON in MongoDB, executed by the workflow worker via RabbitMQ.
//
// Node types:
//   ai_agent     — call an AI agent (groq/nvidia/openrouter)
//   send_message — post a message to a channel
//   send_email   — send an email via nodemailer
//   http_request — call an external webhook/API
//   condition    — if/else branching
//   delay        — wait N seconds before continuing
//
// Trigger types:
//   message_keyword — fires when a message matches a keyword/regex
//   schedule        — cron-based (e.g. every Monday at 9am)
//   webhook         — fires when an incoming webhook is received
//   manual          — only runs when explicitly triggered via API

import mongoose from "mongoose";

const nodeSchema = new mongoose.Schema(
    {
        id:     { type: String, required: true },
        type:   {
            type:    String,
            enum:    ["ai_agent", "send_message", "send_email", "http_request", "condition", "delay"],
            required: true,
        },
        name:   { type: String, required: true },
        // Node-specific configuration — shape depends on type
        config: { type: mongoose.Schema.Types.Mixed, default: {} },
        // Which node to go to next (null = end of workflow)
        nextId: { type: String, default: null },
        // For condition nodes: separate paths for true/false
        trueBranchId:  { type: String },
        falseBranchId: { type: String },
    },
    { _id: false }
);

const workflowSchema = new mongoose.Schema(
    {
        workspaceId: {
            type:     mongoose.Schema.Types.ObjectId,
            ref:      "Workspace",
            required: true,
            index:    true,
        },
        createdBy: {
            type:     mongoose.Schema.Types.ObjectId,
            ref:      "User",
            required: true,
        },
        name: {
            type:      String,
            required:  [true, "Workflow name is required"],
            trim:      true,
            maxlength: [100, "Name must be under 100 characters"],
        },
        description: {
            type:    String,
            default: "",
            maxlength: [500, "Description must be under 500 characters"],
        },
        isEnabled: {
            type:    Boolean,
            default: true,
            index:   true,
        },
        trigger: {
            type: {
                type:   String,
                enum:   ["message_keyword", "schedule", "webhook", "manual"],
                required: true,
            },
            config: { type: mongoose.Schema.Types.Mixed, default: {} },
        },
        nodes: [nodeSchema],
        // Execution stats
        executionCount:   { type: Number, default: 0 },
        lastExecutedAt:   { type: Date },
        lastExecutionStatus: {
            type: String,
            enum: ["success", "failed", "running", null],
            default: null,
        },
        // Whether this workflow was generated by AI
        aiGenerated: {
            type:    Boolean,
            default: false,
        },
        // Template this was forked from (if any)
        templateId: {
            type: mongoose.Schema.Types.ObjectId,
            ref:  "WorkflowTemplate",
        },
    },
    {
        timestamps: true,
    }
);

workflowSchema.index({ workspaceId: 1, isEnabled: 1 });
workflowSchema.index({ workspaceId: 1, "trigger.type": 1 });

const Workflow = mongoose.model("Workflow", workflowSchema);
export default Workflow;
